environment:
    matrix:
        - PYTHON: Python36
        - PYTHON: Python37
        - PYTHON: Python38
        - PYTHON: Python39

install:
    - C:\%PYTHON%\python.exe setup.py install

build: off

test_script:
    - C:\%PYTHON%\python.exe setup.py test
