# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

install:
    - python -m pip install pip -U
    - python -m pip install .
    - python setup.py --quiet install
    - python -m pip coverage python-coveralls

script:
    - python setup.py test

after_success:
    - coverage run --source codemetrics setup.py test
    - coveralls
