# Config file for automatic testing at travis-ci.org

language: python
python:
    - "3.7"
    - "3.6"

install:
    - pip install coverage python-coveralls
    - python setup.py --quiet install

script:
    - python setup.py test

after_success:
    - coverage run --source metrics tests.py
    - coveralls
