[build-system]
# Minimum requirements for the build system to execute.
# See https://github.com/scipy/scipy/pull/10431 for the AIX issue.
requires = [
    "setuptools",
    "wheel",
    "numpy==1.16.5; python_version=='3.7' and platform_system!='AIX'",
    "numpy==1.17.3; python_version=='3.8' and platform_system!='AIX'",
    "numpy==1.16.5; python_version=='3.7' and platform_system=='AIX'",
    "numpy==1.17.3; python_version=='3.8' and platform_system=='AIX'",
    "numpy; python_version>='3.9'",
]
